POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "new blog asdg",
    "author": "buda",
    "url": "www.buda.com"
}

###
PUT http://localhost:3003/api/blogs/657ac94dd1737d590d817a54
Content-Type: application/json

{
    "likes": 1
}