POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer token

{
    "title": "blog with different token",
    "author": "buda",
    "url": "www.buda.com/token"
}

###
PUT http://localhost:3003/api/blogs/657ac94dd1737d590d817a54
Content-Type: application/json

{
    "likes": 1
}