POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer token

{
    "author": "buda",
    "url": "www.buda.com/token"
}

###
PUT http://localhost:3003/api/blogs/657ddd3e1df12e86e11d634c
Content-Type: application/json
Authorization: Bearer token

{
    "likes": 1
}